/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "circulacion.v:1" *)
module circulacionEstruct(IDLE, valid_in0, valid_in1, valid_in2, valid_in3, in0, in1, in2, in3, valid_outp0, valid_outp1, valid_outp2, valid_outp3, outp0, outp1, outp2, outp3, valid_outf0, valid_outf1, valid_outf2, valid_outf3, outf0, outf1, outf2, outf3);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  (* src = "circulacion.v:3" *)
  input IDLE;
  (* src = "circulacion.v:12" *)
  input [7:0] in0;
  (* src = "circulacion.v:13" *)
  input [7:0] in1;
  (* src = "circulacion.v:14" *)
  input [7:0] in2;
  (* src = "circulacion.v:15" *)
  input [7:0] in3;
  (* src = "circulacion.v:36" *)
  output [7:0] outf0;
  (* src = "circulacion.v:37" *)
  output [7:0] outf1;
  (* src = "circulacion.v:38" *)
  output [7:0] outf2;
  (* src = "circulacion.v:39" *)
  output [7:0] outf3;
  (* src = "circulacion.v:24" *)
  output [7:0] outp0;
  (* src = "circulacion.v:25" *)
  output [7:0] outp1;
  (* src = "circulacion.v:26" *)
  output [7:0] outp2;
  (* src = "circulacion.v:27" *)
  output [7:0] outp3;
  (* src = "circulacion.v:6" *)
  input valid_in0;
  (* src = "circulacion.v:7" *)
  input valid_in1;
  (* src = "circulacion.v:8" *)
  input valid_in2;
  (* src = "circulacion.v:9" *)
  input valid_in3;
  (* src = "circulacion.v:30" *)
  output valid_outf0;
  (* src = "circulacion.v:31" *)
  output valid_outf1;
  (* src = "circulacion.v:32" *)
  output valid_outf2;
  (* src = "circulacion.v:33" *)
  output valid_outf3;
  (* src = "circulacion.v:18" *)
  output valid_outp0;
  (* src = "circulacion.v:19" *)
  output valid_outp1;
  (* src = "circulacion.v:20" *)
  output valid_outp2;
  (* src = "circulacion.v:21" *)
  output valid_outp3;
  NOT _037_ (
    .A(in3[3]),
    .Y(_000_)
  );
  NOR _038_ (
    .A(IDLE),
    .B(_000_),
    .Y(outp3[3])
  );
  NOT _039_ (
    .A(in3[4]),
    .Y(_001_)
  );
  NOR _040_ (
    .A(_001_),
    .B(IDLE),
    .Y(outp3[4])
  );
  NOT _041_ (
    .A(in3[5]),
    .Y(_002_)
  );
  NOR _042_ (
    .A(_002_),
    .B(IDLE),
    .Y(outp3[5])
  );
  NOT _043_ (
    .A(in3[6]),
    .Y(_003_)
  );
  NOR _044_ (
    .A(_003_),
    .B(IDLE),
    .Y(outp3[6])
  );
  NOT _045_ (
    .A(in3[7]),
    .Y(_004_)
  );
  NOR _046_ (
    .A(_004_),
    .B(IDLE),
    .Y(outp3[7])
  );
  NOT _047_ (
    .A(IDLE),
    .Y(_005_)
  );
  NOT _048_ (
    .A(in3[0]),
    .Y(_006_)
  );
  NOR _049_ (
    .A(_006_),
    .B(_005_),
    .Y(outf3[0])
  );
  NOT _050_ (
    .A(in3[1]),
    .Y(_007_)
  );
  NOR _051_ (
    .A(_007_),
    .B(_005_),
    .Y(outf3[1])
  );
  NOT _052_ (
    .A(in3[2]),
    .Y(_008_)
  );
  NOR _053_ (
    .A(_008_),
    .B(_005_),
    .Y(outf3[2])
  );
  NOR _054_ (
    .A(_005_),
    .B(_000_),
    .Y(outf3[3])
  );
  NOR _055_ (
    .A(_001_),
    .B(_005_),
    .Y(outf3[4])
  );
  NOR _056_ (
    .A(_002_),
    .B(_005_),
    .Y(outf3[5])
  );
  NOR _057_ (
    .A(_003_),
    .B(_005_),
    .Y(outf3[6])
  );
  NOR _058_ (
    .A(_004_),
    .B(_005_),
    .Y(outf3[7])
  );
  NOT _059_ (
    .A(valid_in2),
    .Y(_009_)
  );
  NOR _060_ (
    .A(_009_),
    .B(IDLE),
    .Y(valid_outp2)
  );
  NOR _061_ (
    .A(_009_),
    .B(_005_),
    .Y(valid_outf2)
  );
  NOT _062_ (
    .A(in2[0]),
    .Y(_010_)
  );
  NOR _063_ (
    .A(_010_),
    .B(IDLE),
    .Y(outp2[0])
  );
  NOT _064_ (
    .A(in2[1]),
    .Y(_011_)
  );
  NOR _065_ (
    .A(_011_),
    .B(IDLE),
    .Y(outp2[1])
  );
  NOT _066_ (
    .A(in2[2]),
    .Y(_012_)
  );
  NOR _067_ (
    .A(_012_),
    .B(IDLE),
    .Y(outp2[2])
  );
  NOT _068_ (
    .A(in2[3]),
    .Y(_013_)
  );
  NOR _069_ (
    .A(_013_),
    .B(IDLE),
    .Y(outp2[3])
  );
  NOT _070_ (
    .A(in2[4]),
    .Y(_014_)
  );
  NOR _071_ (
    .A(_014_),
    .B(IDLE),
    .Y(outp2[4])
  );
  NOT _072_ (
    .A(in2[5]),
    .Y(_015_)
  );
  NOR _073_ (
    .A(_015_),
    .B(IDLE),
    .Y(outp2[5])
  );
  NOT _074_ (
    .A(in2[6]),
    .Y(_016_)
  );
  NOR _075_ (
    .A(_016_),
    .B(IDLE),
    .Y(outp2[6])
  );
  NOT _076_ (
    .A(in2[7]),
    .Y(_017_)
  );
  NOR _077_ (
    .A(_017_),
    .B(IDLE),
    .Y(outp2[7])
  );
  NOR _078_ (
    .A(_010_),
    .B(_005_),
    .Y(outf2[0])
  );
  NOR _079_ (
    .A(_011_),
    .B(_005_),
    .Y(outf2[1])
  );
  NOR _080_ (
    .A(_012_),
    .B(_005_),
    .Y(outf2[2])
  );
  NOR _081_ (
    .A(_013_),
    .B(_005_),
    .Y(outf2[3])
  );
  NOR _082_ (
    .A(_014_),
    .B(_005_),
    .Y(outf2[4])
  );
  NOR _083_ (
    .A(_015_),
    .B(_005_),
    .Y(outf2[5])
  );
  NOR _084_ (
    .A(_016_),
    .B(_005_),
    .Y(outf2[6])
  );
  NOR _085_ (
    .A(_017_),
    .B(_005_),
    .Y(outf2[7])
  );
  NOT _086_ (
    .A(valid_in1),
    .Y(_018_)
  );
  NOR _087_ (
    .A(_018_),
    .B(IDLE),
    .Y(valid_outp1)
  );
  NOR _088_ (
    .A(_018_),
    .B(_005_),
    .Y(valid_outf1)
  );
  NOT _089_ (
    .A(in1[0]),
    .Y(_019_)
  );
  NOR _090_ (
    .A(_019_),
    .B(IDLE),
    .Y(outp1[0])
  );
  NOT _091_ (
    .A(in1[1]),
    .Y(_020_)
  );
  NOR _092_ (
    .A(_020_),
    .B(IDLE),
    .Y(outp1[1])
  );
  NOT _093_ (
    .A(in1[2]),
    .Y(_021_)
  );
  NOR _094_ (
    .A(_021_),
    .B(IDLE),
    .Y(outp1[2])
  );
  NOT _095_ (
    .A(in1[3]),
    .Y(_022_)
  );
  NOR _096_ (
    .A(_022_),
    .B(IDLE),
    .Y(outp1[3])
  );
  NOT _097_ (
    .A(in1[4]),
    .Y(_023_)
  );
  NOR _098_ (
    .A(_023_),
    .B(IDLE),
    .Y(outp1[4])
  );
  NOT _099_ (
    .A(in1[5]),
    .Y(_024_)
  );
  NOR _100_ (
    .A(_024_),
    .B(IDLE),
    .Y(outp1[5])
  );
  NOT _101_ (
    .A(in1[6]),
    .Y(_025_)
  );
  NOR _102_ (
    .A(_025_),
    .B(IDLE),
    .Y(outp1[6])
  );
  NOT _103_ (
    .A(in1[7]),
    .Y(_026_)
  );
  NOR _104_ (
    .A(_026_),
    .B(IDLE),
    .Y(outp1[7])
  );
  NOR _105_ (
    .A(_019_),
    .B(_005_),
    .Y(outf1[0])
  );
  NOR _106_ (
    .A(_020_),
    .B(_005_),
    .Y(outf1[1])
  );
  NOR _107_ (
    .A(_021_),
    .B(_005_),
    .Y(outf1[2])
  );
  NOR _108_ (
    .A(_022_),
    .B(_005_),
    .Y(outf1[3])
  );
  NOR _109_ (
    .A(_023_),
    .B(_005_),
    .Y(outf1[4])
  );
  NOR _110_ (
    .A(_024_),
    .B(_005_),
    .Y(outf1[5])
  );
  NOR _111_ (
    .A(_025_),
    .B(_005_),
    .Y(outf1[6])
  );
  NOR _112_ (
    .A(_026_),
    .B(_005_),
    .Y(outf1[7])
  );
  NOT _113_ (
    .A(valid_in0),
    .Y(_027_)
  );
  NOR _114_ (
    .A(_027_),
    .B(IDLE),
    .Y(valid_outp0)
  );
  NOR _115_ (
    .A(_027_),
    .B(_005_),
    .Y(valid_outf0)
  );
  NOT _116_ (
    .A(in0[0]),
    .Y(_028_)
  );
  NOR _117_ (
    .A(_028_),
    .B(IDLE),
    .Y(outp0[0])
  );
  NOT _118_ (
    .A(in0[1]),
    .Y(_029_)
  );
  NOR _119_ (
    .A(_029_),
    .B(IDLE),
    .Y(outp0[1])
  );
  NOT _120_ (
    .A(in0[2]),
    .Y(_030_)
  );
  NOR _121_ (
    .A(_030_),
    .B(IDLE),
    .Y(outp0[2])
  );
  NOT _122_ (
    .A(in0[3]),
    .Y(_031_)
  );
  NOR _123_ (
    .A(_031_),
    .B(IDLE),
    .Y(outp0[3])
  );
  NOT _124_ (
    .A(in0[4]),
    .Y(_032_)
  );
  NOR _125_ (
    .A(_032_),
    .B(IDLE),
    .Y(outp0[4])
  );
  NOT _126_ (
    .A(in0[5]),
    .Y(_033_)
  );
  NOR _127_ (
    .A(_033_),
    .B(IDLE),
    .Y(outp0[5])
  );
  NOT _128_ (
    .A(in0[6]),
    .Y(_034_)
  );
  NOR _129_ (
    .A(_034_),
    .B(IDLE),
    .Y(outp0[6])
  );
  NOT _130_ (
    .A(in0[7]),
    .Y(_035_)
  );
  NOR _131_ (
    .A(_035_),
    .B(IDLE),
    .Y(outp0[7])
  );
  NOR _132_ (
    .A(_028_),
    .B(_005_),
    .Y(outf0[0])
  );
  NOR _133_ (
    .A(_029_),
    .B(_005_),
    .Y(outf0[1])
  );
  NOR _134_ (
    .A(_030_),
    .B(_005_),
    .Y(outf0[2])
  );
  NOR _135_ (
    .A(_031_),
    .B(_005_),
    .Y(outf0[3])
  );
  NOR _136_ (
    .A(_032_),
    .B(_005_),
    .Y(outf0[4])
  );
  NOR _137_ (
    .A(_033_),
    .B(_005_),
    .Y(outf0[5])
  );
  NOR _138_ (
    .A(_034_),
    .B(_005_),
    .Y(outf0[6])
  );
  NOR _139_ (
    .A(_035_),
    .B(_005_),
    .Y(outf0[7])
  );
  NOT _140_ (
    .A(valid_in3),
    .Y(_036_)
  );
  NOR _141_ (
    .A(_036_),
    .B(IDLE),
    .Y(valid_outp3)
  );
  NOR _142_ (
    .A(_036_),
    .B(_005_),
    .Y(valid_outf3)
  );
  NOR _143_ (
    .A(_006_),
    .B(IDLE),
    .Y(outp3[0])
  );
  NOR _144_ (
    .A(_007_),
    .B(IDLE),
    .Y(outp3[1])
  );
  NOR _145_ (
    .A(_008_),
    .B(IDLE),
    .Y(outp3[2])
  );
endmodule
